Repository konveyor/move2kube-tests, pull requests merged in 2020-12, with the labels that each got.

#26 fix: release workflow to match the cli release workflow
  .github/workflows/assignproject.yml
  .github/workflows/release.yml
  .github/workflows/tag.yml
Labels: bug

#27 fix: typo in slack notification and reformatted workflow files
  .github/workflows/assignproject.yml
  .github/workflows/prtest.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .github/workflows/testtag.yml
Labels: bug

#28 fix: add gren config file so it will generate the proper release draft
  .grenrc.js
Labels: bug

#31 feat: label pull requests based on their title
  .github/workflows/labelpr.yml
Labels: enhancement

#32 fix: Change default dir to workspace
  Dockerfile
  Makefile
Labels: fix

#33 feat: Changes to support fedora as base image
  .github/workflows/labelpr.yml
  Dockerfile
  misc/centos.repo
Labels: feat

#34 fix: Optimize container image size and remove containers after run
  Dockerfile
  Makefile
Labels: fix

#35 ci: clean up workflows to work together across multiple repos
  .github/workflows/assignproject.yml
  .github/workflows/prtest.yml
  .github/workflows/release.yml
  .github/workflows/tag.yml
  .github/workflows/test.yml
  .github/workflows/testtag.yml
Labels: ci

#36 ci: create tag and create branch in release workflow
  .github/workflows/release.yml
  .grenrc.js
Labels: ci

#37 ci: fix bug where the 2 args were being treated as a single arg and passed to GREN
  .github/workflows/release.yml
Labels: ci

#38 ci: we have to login before we can push
  .github/workflows/release.yml
Labels: ci

#39 ci: see https://github.com/konveyor/move2kube/pull/371 for details
  .github/workflows/release.yml
Labels: ci
